"""renamed_roles_enum

Revision ID: 070617fb71ca
Revises: 4026b68e4064
Create Date: 2025-07-26 22:41:09.516285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '070617fb71ca'
down_revision: Union[str, None] = '4026b68e4064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPERADMIN', 'ADMIN', 'USER', name='userroles'),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userroles"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userrole'),
               type_=postgresql.ENUM('SUPERADMIN', 'ADMIN', 'USER', name='userroles'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userroles"))
    # ### end Alembic commands ###
