"""renamed_user_role

Revision ID: 4026b68e4064
Revises: 5d0bf66b5d29
Create Date: 2025-07-26 22:07:03.053416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4026b68e4064'
down_revision: Union[str, None] = '5d0bf66b5d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userroles'), server_default='USER', nullable=False))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ENUM('SUPERADMIN', 'ADMIN', 'USER', name='userroles'), server_default=sa.text("'USER'::userroles"), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
