"""unique bought user coruses

Revision ID: 6386c946bf2a
Revises: 6d8f4582fb0f
Create Date: 2025-08-25 23:25:38.678456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6386c946bf2a'
down_revision: Union[str, None] = '6d8f4582fb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_courses', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_courses', type_='unique')
    # ### end Alembic commands ###
