"""created course model

Revision ID: 72af6c27fa47
Revises: f09a3510b339
Create Date: 2025-07-08 00:38:50.473495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72af6c27fa47'
down_revision: Union[str, None] = 'f09a3510b339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False, comment='A course title'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='Course description'),
    sa.Column('level', sa.Enum('BASIC', 'MEDIUM', 'PROFESSIONAL', name='courselevelenum'), nullable=False, comment='Course level'),
    sa.Column('logo', sa.String(length=512), nullable=False, comment='Path or URL to logo image'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Author ID'),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False, comment='Course is active'),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False, comment='Course rating'),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False, comment='Course price'),
    sa.Column('discount', sa.SmallInteger(), server_default='0', nullable=False, comment='Course discount percentage'),
    sa.Column('currency', sa.Enum('USD', 'EUR', name='currencyenum'), nullable=False, comment='Course currency'),
    sa.Column('language', sa.Enum('EN', 'DE', 'FR', name='availablelanguagesenum'), nullable=False, comment='Course available languages'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_rating'), 'courses', ['rating'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_rating'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
