"""recreated

Revision ID: ac4fadc26f45
Revises: 
Create Date: 2025-07-13 23:17:48.461584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4fadc26f45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userroles'), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('authors',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Author slug'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Author is verified'),
    sa.Column('balance', sa.Numeric(precision=7, scale=2), nullable=False, comment='Author total balance'),
    sa.Column('facebook_url', sa.String(length=255), nullable=True, comment='Facebook URL'),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True, comment='LinkedIn URL'),
    sa.Column('education', sa.String(), nullable=True, comment='Education info'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Contact website'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_authors_slug'), 'authors', ['slug'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.UUID(), nullable=False),
    sa.Column('expires_in', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=False)
    op.create_table('courses',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='A course title'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='Course description'),
    sa.Column('level', sa.Enum('BASIC', 'MEDIUM', 'PROFESSIONAL', name='courselevelenum'), nullable=False, comment='Course level'),
    sa.Column('logo', sa.String(length=512), nullable=False, comment='Path or URL to logo image'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Author ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Course is active'),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False, comment='Course rating'),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False, comment='Course price'),
    sa.Column('discount', sa.SmallInteger(), server_default='0', nullable=False, comment='Course discount percentage'),
    sa.Column('currency', sa.Enum('USD', 'EUR', name='currencyenum'), nullable=False, comment='Course currency'),
    sa.Column('language', sa.Enum('EN', 'DE', 'FR', name='availablelanguagesenum'), nullable=False, comment='Course available languages'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_rating'), 'courses', ['rating'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('user_courses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_courses')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_rating'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_authors_slug'), table_name='authors')
    op.drop_table('authors')
    op.drop_table('users')
    # ### end Alembic commands ###
