"""recreated

Revision ID: ed787a06728b
Revises:
Create Date: 2025-07-12 11:08:29.074151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed787a06728b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userroles'), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False, comment='A course title'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='Course description'),
    sa.Column('level', sa.Enum('BASIC', 'MEDIUM', 'PROFESSIONAL', name='courselevelenum'), nullable=False, comment='Course level'),
    sa.Column('logo', sa.String(length=512), nullable=False, comment='Path or URL to logo image'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Author ID'),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False, comment='Course is active'),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False, comment='Course rating'),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False, comment='Course price'),
    sa.Column('discount', sa.SmallInteger(), server_default='0', nullable=False, comment='Course discount percentage'),
    sa.Column('currency', sa.Enum('USD', 'EUR', name='currencyenum'), nullable=False, comment='Course currency'),
    sa.Column('language', sa.Enum('EN', 'DE', 'FR', name='availablelanguagesenum'), nullable=False, comment='Course available languages'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_rating'), 'courses', ['rating'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.UUID(), nullable=False),
    sa.Column('expires_in', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_rating'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
